table DimProduct
	lineageTag: 6fe12bc7-2160-436e-8625-b179bf452d80

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 9ba2fcd4-59d6-4fe0-b002-c56545ce5509
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 2122f331-eef8-48a3-a65f-e4ecbbb53ccd
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column ProductGroup
		dataType: string
		lineageTag: 1daf6d45-3055-4034-b8d1-1a248bb550fc
		summarizeBy: none
		sourceColumn: ProductGroup

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\perumalm\Documents\Github copilot\Git_Copilot_POC.xlsx"), null, true),
				    DimProduct_Sheet = Source{[Item="DimProduct",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimProduct_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", Int64.Type}, {"Product", type text}, {"ProductGroup", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

